repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: pretty-format-json
        args:
          - --autofix
          - --indent=2
      - id: trailing-whitespace

  - repo: https://github.com/crate-ci/typos
    rev: v1.48.0
    hooks:
      - id: typos

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.28
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.20
    hooks:
      - id: ruff-format
      - id: ruff-check
        args: [--fix, --unsafe-fixes]

  - repo: https://github.com/pycqa/flake8
    rev: "7.3.0"
    hooks:
      - id: flake8
        args: [src/taskiq_clickhouse]
        additional_dependencies:
          - wemake-python-styleguide==1.6.2
        files: ^(?:\.flake8|src/taskiq_clickhouse/.*\.py)$
        pass_filenames: false
        types: [file]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.3.0
    hooks:
      - id: mypy
        additional_dependencies:
          - "clickhouse-connect[async]==1.4.2"
          - "factory-boy==3.3.3"
          - "faker==40.35.0"
          - "pydantic==2.13.4"
          - "pytest-asyncio==1.4.0"
          - "pytest==9.1.1"
          - "taskiq==0.12.4"
        args: [--config-file=pyproject.toml]
        files: ^(?:pyproject\.toml|(?:docs/examples|src/taskiq_clickhouse|tests)/.*\.pyi?)$
        pass_filenames: false
        types: [file]
